import { AllTags } from "./frontmatterToBlogData";

export const displayTag: Record<AllTags, string> = {
  apm: "APM",
  "blog-recent-post": "Recent Post",
  "database-monitoring": "Database Monitoring",
  "distributed-tracing": "Distributed Tracing",
  "dot-net": ".NET",
  "elixir-erlang": "Elixir & Erlang",
  "go-golang": "Go",
  "hero-section": "Hero Section",
  "most-recent-post": "Most Recent Post",
  "open-source": "Open Source",
  "open-telementry-implementations": "Open Telementry Implementations",
  "opentelemetry-instrumentation": "OpenTelemetry Instrumentation",
  "product-updates": "Product Updates",
  "tech-resources": "Tech Resources",
  "tech-tutorial": "Tech Tutorial",
  "tools-comparison": "Tools Comparison",
  community: "Community",
  docker: "Docker",
  jaeger: "Jaeger",
  java: "Java",
  javascript: "JavaScript",
  observability: "Observability",
  opentelemetry: "OpenTelemetry",
  php: "PHP",
  product: "Product",
  prometheus: "Prometheus",
  python: "Python",
  ruby: "Ruby",
  rust: "Rust",
  security: "Security",
  signoz: "Signoz",
  talks: "Talks",
  technical: "Technical",
  tools: "Tools",
};
