import Header from "components/MDX/components/Heading";
import Paragraph from "components/MDX/components/Paragraph";

export default function Privacy() {
  return (
    <div className="md:flex flex-col  justify-center pl-48 pr-56 box-border inline float-none static overflow-wrap ">
      <div>
        <Header type="h1">PRIVACY POLICY</Header>
      </div>
      <Header type="h3">Effective date: 01/01/2021</Header>
      <Header type="h3">1.Introduction</Header>
      <Paragraph>
        Welcome to <span className="font-bold">SigNoz, Inc.</span>
      </Paragraph>
      <Paragraph>
        SigNoz, Inc. (“us”, “we”, or “our”) operates https://signoz.io
        (hereinafter referred to as “Service”).
      </Paragraph>
      <Paragraph>
        Our Privacy Policy governs your visit to https://signoz.io, and explains
        how we collect, safeguard and disclose information that results from
        your use of our Service.
      </Paragraph>
      <Paragraph>
        We use your data to provide and improve Service. By using Service, you
        agree to the collection and use of information in accordance with this
        policy. Unless otherwise defined in this Privacy Policy, the terms used
        in this Privacy Policy have the same meanings as in our Terms and
        Conditions.
      </Paragraph>
      <Paragraph>
        Our Terms and Conditions (“Terms”) govern all use of our Service and
        together with the Privacy Policy constitutes your agreement with us
        (“agreement”).
      </Paragraph>
      <Header type="h3">2.Definitions</Header>
      <Paragraph>
        <span className="font-bold">SERVICE</span> means the https://signoz.io
        website operated by SigNoz, Inc.
      </Paragraph>
      <Paragraph>
        <span className="font-bold">PERSONAL DATA</span> means data about a
        living individual who can be identified from those data (or from those
        and other information either in our possession or likely to come into
        our possession).
      </Paragraph>
      <Paragraph>
        <span className="font-bold">USAGE DATA</span> is data collected
        automatically either generated by the use of Service or from Service
        infrastructure itself (for example, the duration of a page visit).
      </Paragraph>
      <Paragraph>
        <span className="font-bold">COOKIES</span> are small files stored on
        your device (computer or mobile device).
      </Paragraph>
      <Paragraph>
        <span className="font-bold">DATA CONTROLLER</span> means a natural or
        legal person who (either alone or jointly or in common with other
        persons) determines the purposes for which and the manner in which any
        personal data are, or are to be, processed. For the purpose of this
        Privacy Policy, we are a Data Controller of your data.
      </Paragraph>
    </div>
  );
}
